#**Section C: Practical Notebook Build**

##Student Performance Analysis

- This notebook contains a dataset of every student regarding their attendance, diary entries, tasks completed, assignment score and their lab score.

###Tasks:

1. Create and load the dataset and display the first rows.
2. Check data types, missing values, and basic shape.
3. Create a function that calculates final readiness score from attendance, diary, task, assignment, and lab signals.
4. Use loops or apply logic to classify each student into Support, Developing, Strong, or Excellent.
5. Generate at least three analytics outputs: department average, top performer, and students needing support.
6. Add clean Markdown explanation after every major code block.

###**1. Creating and loading a dataset.**

In [ ]:
import pandas as pd

data = {
    "student_id" : ["2026CS001", "2026CS002", "2026IT001","2026IT002",
                  "2026CE001","2026CE002","2026CS003","2026IT003"],
    "name" : ["Aditi","Bhavana","Chaitra","Divya",
            "Esha","Fatima","Gauri","Harshada"],
    "department" : ["Computer Engineering","Computer Engineering",
                  "Information Technology","Information Technology",
                  "Civil Engineering","Civil Engineering",
                  "Computer Engineering","Information Technology"],
    "attendance_pct" : [92,64,78,55,88,71,96,43],
    "diary_entries" : [12,6,9,4,10,8,14,2],
    "tasks_completed" : [8,5,7,3,8,6,9,2],
    "assignment_score" : [84,58,72,46,79,66,91,35],
    "lab_score" : [88,61,76,52,82,69,94,41]
}

df = pd.DataFrame(data)

df.to_csv("week_2_3_exam_student_signals.csv", index=False)

df = pd.read_csv("week_2_3_exam_student_signals.csv")

df.head()

,student_id,name,department,attendance_pct,diary_entries,tasks_completed,assignment_score,lab_score
0,2026CS001,Aditi,Computer Engineering,92,12,8,84,88
1,2026CS002,Bhavana,Computer Engineering,64,6,5,58,61
2,2026IT001,Chaitra,Information Technology,78,9,7,72,76
3,2026IT002,Divya,Information Technology,55,4,3,46,52
4,2026CE001,Esha,Civil Engineering,88,10,8,79,82

###Dataset Preview:
The dataset has been created and the first five records are displayed.

###**2. Data Inspection**

In [12]:
print("\nData Types:\n", df.dtypes)

print("\nMissing values:\n", df.isnull().sum())

print("\nShape: ", df.shape)

Data Types:
 student_id          object
name                object
department          object
attendance_pct       int64
diary_entries        int64
tasks_completed      int64
assignment_score     int64
lab_score            int64
dtype: object

Missing values:
 student_id          0
name                0
department          0
attendance_pct      0
diary_entries       0
tasks_completed     0
assignment_score    0
lab_score           0
dtype: int64

Shape:  (8, 8)

### Data Inspection:
This code block checks the dataset for the data types, any missing values, dataset size.

### **3. Readiness Function**

In [13]:
def readiness_score(attendance_pct, diary_enteries, tasks_completed, assignment_score, lab_score):
  score = attendance_pct * 0.30
  score += diary_enteries * 2
  score += tasks_completed * 3
  score += assignment_score * 0.20
  score += lab_score * 0.20

  return min(round(score, 2), 100)

df["readiness_score"] = df.apply(lambda row: readiness_score(row["attendance_pct"], row["diary_entries"], row["tasks_completed"], row["assignment_score"], row["lab_score"]), axis=1)

df[["name", "readiness_score"]]

       name  readiness_score
0     Aditi            100.0
1   Bhavana             70.0
2   Chaitra             92.0
3     Divya             53.1
4      Esha            100.0
5    Fatima             82.3
6     Gauri            100.0
7  Harshada             38.1

### Readiness Score:
The readiness score is calculated by this function using attendace, diary entries, completed tasks, assignment scorea and lab scores from the dataset.

### **4. Classification**

In [14]:
def performance_band(score):
    if score < 40:
        return "Support"

    elif score < 70:
        return "Developing"

    elif score < 90:
        return "Strong"

    else:
        return "Excellent"
bands = []

for score in df["readiness_score"]:
    bands.append(performance_band(score))

df["Performance_Band"] = bands

df[["name","readiness_score","Performance_Band"]]

       name  readiness_score Performance_Band
0     Aditi            100.0        Excellent
1   Bhavana             70.0           Strong
2   Chaitra             92.0        Excellent
3     Divya             53.1       Developing
4      Esha            100.0        Excellent
5    Fatima             82.3           Strong
6     Gauri            100.0        Excellent
7  Harshada             38.1          Support

###Performance Calculation:
Students are classified into Support, Developing, Strong, Excellent categories respectively.

### **5. Analytics**

In [15]:
print("\nDepartment Average Readiness Score")

print(df.groupby("department")["readiness_score"].mean())

print("\nTop Performer")

top = df.loc[df["readiness_score"].idxmax()]
print(top[["name","department","readiness_score"]])

print("\nStudents Needing Support")

support = df[df["Performance_Band"]=="Support"]

print(support[["student_id","name","department","readiness_score"]])

Department Average Readiness Score
department
Civil Engineering         91.150000
Computer Engineering      90.000000
Information Technology    61.066667
Name: readiness_score, dtype: float64

Top Performer
name                              Aditi
department         Computer Engineering
readiness_score                   100.0
Name: 0, dtype: object

Students Needing Support
  student_id      name              department  readiness_score
7  2026IT003  Harshada  Information Technology             38.1

###Final Analytics:
This notebook generates the department wise average readiness score of every student from the dataset, top performing student and students who need specical support.

---
#**Section D: Data Analytics Interpretation**

##**1. Which department appears strongest in the dataset and why?**
###***Answer:***
The Computer Engineering department appears to be the strongest. It has students with high attendance, good assignment and lab scores, and the highest readiness scores. Students like Aditi and Gauri consistently perform well across most performance indicators.


##**2. Which students need immediate academic support and what signals show that?**
###***Answer:***
Divya and Harshada need immediate academic support. These students have low attendance, fewer diary entries, fewer completed tasks, and lower assignment and lab scores. These signals indicate that they may require additional guidance and academic assistance.


##**3. What is one limitation of this small dataset?**
###***Answer:***
The dataset contains only 8 students, which is too small to represent the overall performance of an entire department or college. The results may not generalize to a larger student population.


##**4. What extra columns would make the analysis more useful for the internship team?**
###***Answer:***
Internal test or quiz scores, Project completion status, Student participation or classroom engagement, Placement readiness or technical skill assessment features would provide a more enhanced view of each students academic performance and readiness.